import os

MONGODB_USER = os.getenv('MONGODB_USER')
MONGODB_PASSWD = os.getenv('MONGODB_PASSWD')
MONGODB_NAME = os.getenv('MONGODB_NAME')
MONGODB_HOST = os.getenv('MONGODB_HOST')

SECRET_KEY = os.getenv('SECRET_KEY')
AUTH_SERVICE_JWT_SECRET = os.getenv('AUTH_SERVICE_JWT_SECRET')
