---
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gwlab-gwcandidate-nginx
  namespace: gwcloud
  labels:
    name: gwlab-gwcandidate-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
        name: gwlab-gwcandidate-nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        name: gwlab-gwcandidate-nginx
    spec:
      containers:
        - name: gwlab-gwcandidate-nginx
          image: nexus.gwdc.org.au/docker/gwlab_gwcandidate_nginx:0.1
          ports:
            - name: http
              containerPort: 8000
          resources: {}
          tty: true
      imagePullSecrets:
      - name: regcred
... 
