apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: vault-agent
    app.kubernetes.io/instance: gwcandidate
  name: secrets-integrator-gwcandidate
  namespace: gwcloud
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      labels:
        app: vault-kube-integrator
    spec:
      backoffLimit: 1
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-init-first: 'true'
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/agent-inject-secret-gwcandidate.yaml: gwcloud/kv/gwcandidate
            vault.hashicorp.com/agent-inject-template-gwcandidate.yaml: |
              {{- with secret "gwcloud/kv/gwcandidate" -}}
              apiVersion: v1
              kind: Secret
              type: Opaque
              stringData:
                {{ range $k, $v := .Data.data }}
                {{ $k }}: {{ $v }}
                {{ end }}
              metadata:
                namespace: gwcloud
                name: gwcandidate
              {{- end }}
            vault.hashicorp.com/agent-pre-populate-only: 'true'
            vault.hashicorp.com/role: gwcandidate
        spec:
          containers:
            - command:
                - kubectl
                - apply
                - '-f'
                - /vault/secrets/
              image: 'bitnami/kubectl:1.17.4'
              imagePullPolicy: IfNotPresent
              name: gwcandidate-vault-kube-integrator
              resources: {}
          imagePullSecrets:
            - name: regcred
          restartPolicy: Never
          serviceAccountName: gwcandidate
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 1
