resources:
  - gwlab_gwcandidate_vault_secrets_integrator.yaml
  - gwlab_gwcandidate_vault_rbac.yaml
  - gwlab_gwcandidate_django_deployment.yaml
  - gwlab_gwcandidate_django_service.yaml
  - gwlab_gwcandidate_nginx_deployment.yaml
  - gwlab_gwcandidate_nginx_service.yaml
  - gwlab_gwcandidate_static_deployment.yaml
  - gwlab_gwcandidate_static_service.yaml
